# LitmusChaos Fault Injection - litmuschaos-experiment.yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-delete-chaos
  namespace: chaos-testing
spec:
  appinfo:
    appns: t2s-app
    applabel: app=backend
    appkind: deployment
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60" # Duration in seconds
            - name: CHAOS_INTERVAL
              value: "10"
            - name: FORCE
              value: "false"
