# HashiCorp Vault Setup - vault-setup.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vault-credentials
  namespace: security
type: Opaque
data:
  VAULT_TOKEN: "base64-encoded-token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:latest
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          valueFrom:
            secretKeyRef:
              name: vault-credentials
              key: VAULT_TOKEN
