# ConfigMap for Environment Variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: t2s-app
data:
  DATABASE_HOST: "database-host"
  DATABASE_PORT: "5432"
  LOG_LEVEL: "INFO"
