# values.yaml - Default Values for Helm Chart
replicaCount: 2

image:
  repository: t2s-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "alb"
  hosts:
    - host: frontend.t2s-app.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port:
                number: 80
