# ArgoCD GitOps Deployment - argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t2s-app
  namespace: argocd
spec:
  destination:
    namespace: t2s-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Here2ServeU/t2s-sre-platform.git
    path: helm/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
